### ISSUE TITLE
Proper package missing from latest release.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/honeypot#15]
https://github.com/backdrop-contrib/honeypot/releases

...no "Download honeypot 1.0.6 (zip)" link like the previous releases had. Only source code in .zip and .tar.gz format.

**Comment by herbdool** [comment]
Huh, weird. Why did this happen and what can be done? @klonos

**Comment by klonos** [comment]
It happens for other projects too. So I filed an issue against backdropcms.org: https://github.com/backdrop-ops/backdropcms.org/issues/264

Sorry, I forgot to close this issue here.
