### ISSUE TITLE
php error: Call to undefined function save() in honeypot_update_1004() (line 176 of honeypot.install)

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/honeypot#16]
`Error: Call to undefined function save() in honeypot_update_1004() (line 176 of /var/www/modules/honeypot/honeypot.install).`

This is on 1.4.3 upgrading 1.0.5 to 1.0.6

**Comment by klonos** [comment]
The error as shown during update.php run:

> An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://my.site.net/core/update.php?op=selection&token=[some_token]&id=11&op=do_nojs&op=do StatusText: Service unavailable (with message) ResponseText: Error: Call to undefined function save() in honeypot_update_1004() (line 176 of /var/www/userfriendly.tech/modules/honeypot/honeypot.install).

**Comment by herbdool** [comment]
Oops! thanks for the catch @klonos. I've fixed and made another release. (I've got to do some more testing before I make releases!)
