### ISSUE TITLE
Clean up README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/honeypot#3]
Thanks for this port @herbdool :) Honeypot is one of my favorite modules!

Do you think I could talk you into changing the formatting of first heading in the README.md file?

backdropcms.org is set up to remove the first heading when properly formatted. If that heading is not formatted correctly, it won't be removed.  (Please refer to our [contributor guidelines](https://github.com/backdrop-ops/contrib) for an [example README.md](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) file)

Take a look at the modules list to see the problem:
https://backdropcms.org/modules?keys=honeypot

**Comment by herbdool** [comment]
done. but curious, with this small change does it make sense to update the existing release or create a new sub-point release?

**Comment by jenlampton** [comment]
I'd say don't worry about it yet, the next time you make a release it will be fixed and that's good enough to make me happy :)
