### ISSUE TITLE
Schema version set to 2001 instead of 1001 in last update.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/honeypot#7]
A typo, likely. but should be fixed, otherwise we're going to have some issues when Backdrop 2 is out :)

**Comment by CybersecDan** [comment]
Is this what you're referring too in the `honeypot.install` file:

``` /**
 * Ensure a css file is created
 */
function honeypot_update_2001() {
  backdrop_load('module', 'honeypot');
  module_load_include('inc', 'honeypot', 'honeypot.admin');
  honeypot_create_css(config_get('honeypot.settings', 'element_name'));
}
```

**Comment by jenlampton** [comment]
yes, `function honeypot_update_2001() {` should be `function honeypot_update_1001() {` and that whole function should be located (in the file) above the closing docblock that says "things after this should start with 2000" :)

**Comment by CybersecDan** [comment]
Gotcha. Mind if I give it a try?

**Comment by jenlampton** [comment]
please do! :)

**Comment by CybersecDan** [comment]
Just opened a PR. Hope I did it right. : /   I need to do this way more often to get this process down without any worries. ha. #8

**Comment by CybersecDan** [comment]
Also just realized that my branch number is 7, instead of 8. Sorry. I know we like to keep the branch names corresponding to the issue number.

**Comment by herbdool** [comment]
Thanks @danielrose28 and @jenlampton. Merged!

**Comment by klonos** [comment]
I just upgraded my website from 1.0.2 to 1.0.3 and it doesn't have any message about the db needing to be updated??

**Comment by CybersecDan** [comment]
That might be normal, no? I've run into that before with implementing a module update, then `update.php`, only to find nothing needed to be updated, but the new functionality was in fact updated. Not sure why that is. Just a thought. I'm open to suggestions, pro tips, etc., and I can take a look at the code again.
